FROM qdocker/base:7
RUN mkdir /sw
RUN yum install -y cmake.x86_64
#ADD nginx-1.9.3.tar.gz /sw/
#ADD install_nginx.sh /sw/install_nginx.sh
#RUN /bin/sh /sw/install_nginx.sh
#
#ENTRYPOINT /nginx/sbin/nginx && /bin/bash
#
#
#
